### ISSUE TITLE
Code for those on-policy algorithms

### ISSUE THREAD

**Issue by grandpahao** [liuzuxin/cvpo-safe-rl#2]
Hi~ 
I do not find codes of on-policy algorithms in this repo. 
Do you have any examples of PPO with lagrangian multipliers?

**Comment by liuzuxin** [comment]
Hi @grandpahao,

I use the original [safety-starter-agents](https://github.com/openai/safety-starter-agents) as the on-policy baselines in the paper, see the third paragraph here: https://github.com/liuzuxin/cvpo-safe-rl#notes-and-acknowledgments.
Recently I found another repo contains the implementations of PPO-L, TRPO-L, and CPO, see https://github.com/PKU-MARL/Safe-Policy-Optimization. Thanks.

**Comment by grandpahao** [comment]
A lot of thanks for your answer~
