### ISSUE TITLE
About the term ``max_q`` used in the dual function.

### ISSUE THREAD

**Issue by Zarzard** [liuzuxin/cvpo-safe-rl#5]
Hi! I wonder what role does the term ``max_q`` play in the implementation of the [dual function](https://github.com/liuzuxin/cvpo-safe-rl/blob/main/safe_rl/policy/cvpo.py#L345). This term seems not mentioned in the paper, did I miss anything?

**Comment by liuzuxin** [comment]
Hi @Zarzard , `max_q` is a trick to prevent the number in `exp()` explode. It improves numerical stability without affecting the final results. You can also find the same trick in PyTorch's `logsumexp` function, see [here](https://github.com/pytorch/pytorch/issues/2591#issuecomment-338980717)

**Comment by Zarzard** [comment]
Got it, thanks!
