### ISSUE TITLE
where is default_config.yaml

### ISSUE THREAD

**Issue by xzhang2523** [liuzuxin/cvpo-safe-rl#8]
It says:
FileNotFoundError: [Errno 2] No such file or directory: 'safe_rl/config/default_config.yaml'

**Comment by liuzuxin** [comment]
Hi @xzhang2523 ,could you provide the commands you executed that output this message? 
Note that the config files are located in the `script/config` folder. To run the code, you have to use the `script/run.py` or `script/experiment.py`, as described in the instructions.
